services:
  db:
    image: postgres:15-alpine
    container_name: millionaireasy-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Mexc123!
      - POSTGRES_DB=mexc
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - millionaireasy-net

  redis:
    image: redis:7-alpine
    container_name: millionaireasy-redis
    ports:
      - "6379:6379"
    networks:
      - millionaireasy-net

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: millionaireasy-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=Mexc123!
    networks:
      - millionaireasy-net

  backend:
    container_name: millionaireasy-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/mexc
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=Mexc123!

      - SPRING_DATA_REDIS_HOST=redis

      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_USERNAME=admin
      - SPRING_RABBITMQ_PASSWORD=Mexc123!
    depends_on:
      - db
      - redis
      - rabbitmq
    networks:
      - millionaireasy-net

  frontend:
    container_name: millionaireasy-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - millionaireasy-net

networks:
  millionaireasy-net:
    driver: bridge

volumes:
  postgres-data: