mexc:
  websocket:
    url: "wss://wbs-api.mexc.com/ws"

spring:
  application:
    name: backend
    cors:
      allowed-origins: "http://localhost:5173, frontend:5173, *"
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/mexc}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:Mexc123!}
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  flyway:
    enabled: true
    baseline-version: 0
    baseline-on-migrate: true
    locations: classpath:db/migration
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: 6379
      repositories:
        enabled: false

  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: 5672
    username: ${SPRING_RABBITMQ_USERNAME:admin}
    password: ${SPRING_RABBITMQ_PASSWORD:Mexc123!}
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 5000ms
    template:
      retry:
        enabled: true

application:
  security:
    jwt:
      secret-key: 8a4f9a0b9a8d0c1e3f5a3b2c1d0e9f8a7b6c5d4e3f2a1b0c9d8e7f6a5b4c3d2e
      expiration: 86400000 # 24 horas em milissegundos

jasypt:
  encryptor:
    password: "${JASYPT_ENCRYPTOR_PASSWORD:hardcodedDefaultPasswordForDevOnly}"
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator